title: "Renan Cambre - Data Engineer Portfolio"
email: renancambre@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my professional portfolio where I showcase my data engineering projects and skills.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://renancambre.github.io" # the base hostname & protocol for your site
twitter_username: renancambre
github_username:  renancambre

theme: minima

plugins:
  - jekyll-feed
